### ISSUE TITLE
predict function - ventricles

### ISSUE THREAD

**Issue by math1tvk** [tadpole-share/tadpole-algorithms#1]
** ventricles_prediction = self.adas_model.predict(test_df)
I think, this should be self.ventricles_model.predict(test_df)

1- file "tadpole_algorithms/models/bechmark_svm/__init__.py" line 111
2- file "/tadpole_algorithms/models/emceb/__init__.py" line 207

**Comment by bronesther** [comment]
Wow, good find! Thanks! I am changing it in the code.
