### ISSUE TITLE
Image data ID

### ISSUE THREAD

**Issue by gaody9527** [tadpole-share/tadpole-algorithms#8]
I have registrion and log in LONI, then run the 'selectImgToDownloadD12BiasCorr.py' , get the 'imageIDs'. But when I search in the 'ADVANCED IMAGE SEARCH (beta)' page, there is 0 item. What the  'imageIDs' means, is it the 'Image ID' in the 'ADVANCED IMAGE SEARCH (beta)' page?

**Comment by bronesther** [comment]
Hi Gaody,

I do not completely understand your question. Where do you find selectImgToDownloadD12BiasCorr.py; it is not part of our tadpole-algorithms project, right? Do I understand correctly that your question is about downloading ADNI MRI scans from the LONI website? 

Kind regards,
Esther

**Comment by gaody9527** [comment]
Oh,  my mistake, it is from the official dataset in csv format. sorry and thank you for your reply.
